# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsformer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Skills'),
        ),
    ]
