# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsformer', '0010_auto_20160901_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='subjects',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject'),
        ),
    ]
