# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 20:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsformer', '0013_auto_20160905_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='developer',
            field=models.ForeignKey(blank=True, default='Vacant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_developer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_contact_list_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
