# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 10:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsformer', '0014_auto_20160907_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='request',
            field=models.ManyToManyField(blank=True, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='team',
            name='developer',
        ),
        migrations.AddField(
            model_name='team',
            name='developer',
            field=models.ManyToManyField(blank=True, related_name='teams_developer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='team',
            name='investor',
        ),
        migrations.AddField(
            model_name='team',
            name='investor',
            field=models.ManyToManyField(blank=True, related_name='teams_investor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='team',
            name='sales_person',
        ),
        migrations.AddField(
            model_name='team',
            name='sales_person',
            field=models.ManyToManyField(blank=True, related_name='teams_sales_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_list',
            field=models.ManyToManyField(blank=True, related_name='_user_contact_list_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
