# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsformer', '0016_team_needs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='needs',
            field=models.CharField(blank=True, null=True, max_length=100, verbose_name='Vacant places'),
        ),
    ]
