# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 14:20
from __future__ import unicode_literals

from django.db import migrations
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsformer', '0019_auto_20160908_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='needs',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('DV', 'Developer'), ('IN', 'Investor'), ('SP', 'Sales person')], max_length=50, null=True, verbose_name='Vacant places'),
        ),
    ]
