# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsformer', '0021_auto_20160908_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('DV', 'Developer'), ('IN', 'Investor'), ('SP', 'Sales person')], default=None, max_length=40, verbose_name='User role'),
        ),
    ]
