# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsformer', '0022_auto_20160912_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='Team details'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, default='noimage.png', upload_to='teams/images/', verbose_name='Team image'),
        ),
        migrations.AlterField(
            model_name='team',
            name='needs',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('Developer', 'Developer'), ('Investor', 'Investor'), ('Sales Person', 'Sales person')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='subjects',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, default=None, verbose_name='Other information'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='noimage.png', upload_to='users/avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, default=None, verbose_name='Skills'),
        ),
    ]
