# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 11:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsformer', '0025_auto_20160912_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, default=None, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Claims',
                'verbose_name': 'Claim',
            },
        ),
        migrations.RemoveField(
            model_name='team',
            name='request',
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, upload_to='teams/images/', verbose_name='Team image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Investor', 'Investor'), ('Sales Person', 'Sales person')], default=None, max_length=40, verbose_name='User role'),
        ),
        migrations.AddField(
            model_name='claim',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='teamsformer.Team'),
        ),
        migrations.AddField(
            model_name='claim',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims_to_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
