# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsformer', '0027_auto_20160915_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Investor', 'Investor'), ('Sales Person', 'Sales person')], default=None, max_length=40, verbose_name='User role'),
        ),
    ]
