# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsformer', '0028_auto_20160915_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='needs',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('Developer', 'Developer'), ('Investor', 'Investor'), ('Sales person', 'Sales person')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Investor', 'Investor'), ('Sales person', 'Sales person')], default=None, max_length=40, verbose_name='User role'),
        ),
    ]
