# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 12:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsformer', '0029_auto_20160916_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created data'),
        ),
    ]
