# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 14:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsformer', '0030_claim_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=None, verbose_name='Text of message')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created data')),
                ('is_new', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(max_length=40, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recive_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(max_length=40, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
