# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsformer', '0033_auto_20160917_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ManyToManyField(related_name='messages', to='teamsformer.Message')),
                ('users', models.ManyToManyField(related_name='dialogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
