# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsformer', '0034_dialog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialog',
            options={'ordering': ['created_date'], 'verbose_name': 'Dialog', 'verbose_name_plural': 'Dialogs'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_date'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='dialog',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created data'),
        ),
    ]
