# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsformer', '0035_auto_20160917_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='messages',
        ),
        migrations.AddField(
            model_name='message',
            name='dialog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='teamsformer.Dialog'),
        ),
    ]
