# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsformer', '0039_auto_20160919_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
    ]
