# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsformer', '0040_dialog_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(default=None, max_length=400, verbose_name='Text of message'),
        ),
    ]
