# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 14:09
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsformer', '0041_auto_20160920_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date of invite')),
                ('comment', models.TextField(blank=True, default=None, max_length=255)),
                ('accepted', models.BooleanField(default=False)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_users', to='teamsformer.Team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites_to_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invite',
                'ordering': ['-created_date'],
                'verbose_name_plural': 'Invites',
            },
        ),
        migrations.AlterField(
            model_name='claim',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created date'),
        ),
    ]
