# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsformer', '0042_auto_20160920_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of invite'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Other information'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Investor', 'Investor'), ('Sales person', 'Sales person')], default=None, max_length=40, null=True, verbose_name='User role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Skills'),
        ),
    ]
