# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 11:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsformer', '0047_auto_20161010_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 17, 11, 6, 3, 343468), verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 17, 11, 6, 3, 343468), verbose_name='Updated date'),
        ),
        migrations.AlterField(
            model_name='team',
            name='needs',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('Developer', 'Developer'), ('Investor', 'Investor'), ('Salesperson', 'Salesperson')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Investor', 'Investor'), ('Salesperson', 'Salesperson')], default=None, max_length=40, null=True, verbose_name='User role'),
        ),
    ]
