# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 11:19
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsformer', '0049_auto_20161017_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='sales_person',
        ),
        migrations.AddField(
            model_name='team',
            name='salesperson',
            field=models.ManyToManyField(blank=True, related_name='teams_salesperson', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 17, 11, 19, 30, 223351), verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 17, 11, 19, 30, 223351), verbose_name='Updated date'),
        ),
    ]
